### ISSUE TITLE
vaadin-input is not getting focused when it's wrapped in <label> tag

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-input#7]
```
<label>
  <vaadin-input></vaadin-input>
</label>
```

![recorded](https://cloud.githubusercontent.com/assets/6059356/22406683/f23d0b14-e65f-11e6-8afd-9459ae376d6f.gif)

```
<label>
  <input>
</label>
```

![recorded](https://cloud.githubusercontent.com/assets/6059356/22406692/169bbcee-e660-11e6-91a5-80aca1def0f9.gif)

Linux/Chrome

Probably related to #5

**Comment by limonte** [comment]
`paper-input` works fine with this case: https://jsbin.com/genolugelu/1/edit?html,console,output

**Comment by manolo** [comment]
@limonte have tried with paper-input#2.0-preview? it seems not working.

```
$ bower i paper-input#2.0-preview
$ cat index.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <script src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>
  <link rel="import" href="bower_components/paper-input/paper-input.html">
</head>
<body>
  <label>
    native label
    <paper-input label="text input"></paper-input>
  </label>
</body>
</html>
```

**Comment by manolo** [comment]
@limonte, your jsbin also fails if you enable shadow

https://jsbin.com/wanuxuzuyo/edit?html,console,output

So I guess it's a user case that we have to re-consider

**Comment by manolo** [comment]
BTW, since the `<label>` spec says that it is for `<input>` elements, wrapping anything not being an input does not work. For instance a `<div tabindex="0">`. Thus, it is impossible to have any custom element supporting this feature in shadow dom.

This does not work
```
<label for="foo"> <div tabindex="0" id="foo"> Foo </div> </label>
```

So the conclusion is that in shady dom, `label` click works out-of-the-box because the nested `input` is selectable, either it is the first child of the label or it is nested.

**Comment by platosha** [comment]
Decided not to fix now, because a proper fix would be pretty complex, while the importance of this use case is unclear at the moment.
